services:
  sqlite-backend:
    build:
      context: ./sqlite-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      # Allow local dev via browser on host
      - CORS_ORIGINS=http://localhost:3000,http://localhost:3001
      # Persist DB outside the container
      - DB_FILE=/data/enatega.db
      - PORT=4000
    volumes:
      - ./enatega.db:/data/enatega.db
    ports:
      - '4000:4000'
    tty: true

  web:
    build:
      context: ./multivendor-web
    volumes:
      - ./multivendor-web:/app
      - web_node_modules:/app/node_modules
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      # Use localhost so the browser (on host) can reach the API published on port 4000
      - NEXT_PUBLIC_SERVER_URL=http://localhost:4000/
    depends_on:
      - sqlite-backend
    tty: true

  admin:
    build:
      context: ./multivendor-admin
    volumes:
      - ./multivendor-admin:/app
      - admin_node_modules:/app/node_modules
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=1
      - NEXT_PUBLIC_SERVER_URL=http://localhost:4000/
      - NEXT_PUBLIC_WS_SERVER_URL=ws://localhost:4000/
    depends_on:
      - sqlite-backend
    tty: true
    user: "node"

volumes:
  web_node_modules:
  admin_node_modules:

networks:
  default:
    driver: bridge
